version: '3.8'
services:
  neo4j:
    container_name: neo4j
    image: neo4j
    ports:
      - "7474:7474"  
      - "7687:7687"  
    environment:
      NEO4J_AUTH: neo4j/test1234

    volumes:
      - ./neo4j-data:/data
      - ./neo4j-import:/import 
    restart: unless-stopped
